name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: "0 6,12 * * *"
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.1.0
        env:
          RENOVATE_REPOSITORIES: '[{ repository: "stakekit/dapp", bumpVersion: true }]'
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.create_token.outputs.token }}
